version: "3.8"

services:
  signalr:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "32781:80"
      - "32782:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  frontsignalr:
    build: .
    ports:
      - "4200:4200"
      - "49153:49153"
    environment:
      - BACKEND_API_URL=https://localhost:32782