version: "3.8"
services:
  signalr:
    image: ${DOCKER_REGISTRY-}signalr
    build:
      context: .
      dockerfile: Backend/SignalR/Dockerfile
  frontsignalr:
    image: ${DOCKER_REGISTRY-}frontsignalr
    build:
      context: .
      dockerfile: Frontend/SignalRClient/signal-monitoring-ui/Dockerfile
    volumes:
      - "/app/node_modules"
      - ".:/app"
